name: AtypicalPrototype
favicon: null
layout_spectrum: 0.849798236740753
typography_spectrum: 0.9919756290037185
title: AtypicalPrototype
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5a6a8'
    - '#101010'
    - '#40413c'
    - '#ffffff'
    - '#7b7b7b'
  brandStrength: 1
  lightness: 0.37665125308558345
  saturation: 0.09558177040889859
  rhythmicContrast: 0.6120848890859634
purpose: []
